apiVersion: enterprisesearch.k8s.elastic.co/v1
kind: EnterpriseSearch
metadata:
  name: enterprisesearch-prod
  namespace: elastic-prod
spec:
  version: 8.11.3
  count: 1
  elasticsearchRef:
    name: elasticsearch-prod
    namespace: elastic-prod
