apiVersion: autoscaling.k8s.elastic.co/v1alpha1
kind: ElasticsearchAutoscaler
metadata:
  name: elasticsearch-prod-autoscaler
  namespace: elastic-prod
spec:
  elasticsearchRef:
    name: elasticsearch-prod
  policies:
  - name: data-ingest
    roles: ["master", "data", "ingest", "remote_cluster_client", "transform"]
    resources:
      nodeCount:
        min: 3
        max: 8
      cpu:
        min: 2
        max: 8
      memory:
        min: 2Gi
        max: 16Gi
      storage:
        min: 10Gi
        max: 512Gi
  - name: ml
    roles:
    - ml
    resources:
      nodeCount:
        min: 1
        max: 9
      cpu:
        min: 1
        max: 4
      memory:
        min: 2Gi
        max: 8Gi
      storage:
        min: 1Gi
        max: 1Gi
