apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- path: elasticsearch-patch.yml
  target:
    group: elasticsearch.k8s.elastic.co
    kind: Elasticsearch
    name: elasticsearch
    version: v1

