apiVersion: maps.k8s.elastic.co/v1alpha1
kind: ElasticMapsServer
metadata:
  name: maps-server-prod
  namespace: elastic-prod
spec:
  version: 8.11.2
  count: 1
  elasticsearchRef:
    name: elasticsearch-prod
    namespace: elastic-prod
