apiVersion: apps/v1
kind: Deployment
metadata:
  name: epr-prod
  namespace: elastic-prod
  labels:
    app.kubernetes.io/name: epr
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: epr
  template:
    metadata:
      labels:
        app.kubernetes.io/name: epr
    spec:
      containers:
      - name: epr
        image: docker.elastic.co/package-registry/distribution:8.15.1
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: 1Gi
            cpu: 200m
          requests:
            memory: 1Gi
            cpu: 200m
---
# in kibana configs add xpack.fleet.registryUrl: "http://epr-prod.elastic-prod.svc.cluster.local:8080"
apiVersion: v1
kind: Service
metadata:
  name: epr-prod
  namespace: elastic-prod
spec:
  selector:
    app.kubernetes.io/name: epr
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080

